### ISSUE TITLE
Conditional test in configure.ac: MPI includepath , libpath 

### ISSUE THREAD

**Issue by roodnejm** [RBigData/pbdMPI#56]
Hello, 

I have tried to installed pbdMPI. The following message appears "Must specify both the include and lib paths". However i have seen in file configure.ac there are two conditional tests line 75 which i maybe do not understand correctly which could raise the error: 

if test -n "${MPI_INCLUDE_PATH}" -a -z "${MPI_LIBPATH}" ; then
  AC_MSG_ERROR([Must specify both the include and lib paths])
fi
if test -z "${MPI_INCLUDE_PATH}" -a -n "${MPI_LIBPATH}" ; then
  AC_MSG_ERROR([Must specify both the include and lib paths])
fi

My "mpi include path" and "lib path" are both setted but conditional tests cited above seem to raise error in any case ("-z" and "-n" on library path) I have a libpath setted or not. Is there something i have missed ? 

Thank you in advance

**Comment by snoweye** [comment]
- `-z` string: True if string is empty.
- `-n` string:True if string is not empty.
It needs both MPI_INCLUDE_PATH and MPI_LIBPATH ready when you reach these two checks, otherwise an error message will be raised.

What is your `R CMD INSTALL` command?

**Comment by roodnejm** [comment]
The command is: R CMD INSTALL pbdMPI

And it raise the following message: 

* installing to library ‘/applis/Rstudio/libs’
* installing *source* package ‘pbdMPI’ ...
** package ‘pbdMPI’ successfully unpacked and MD5 sums checked
setting mpi include path from MPI_INCLUDE
configure: error: Must specify both the include and lib paths
ERROR: configuration failed for package ‘pbdMPI’
* removing ‘/applis/Rstudio/libs/pbdMPI’

Thank you for your time

**Comment by snoweye** [comment]
FYI https://github.com/RBigData/pbdMPI/blob/master/inst/doc/pbdMPI-guide.pdf

- Page 3 at pbdMPI vignettes.
- FAQ may have answers related.

**Comment by roodnejm** [comment]
Thank you and sorry for the inconvenience.

**Comment by snoweye** [comment]
You are welcomed. Let me know if the solutions don't work with Rstudio.
