### ISSUE TITLE
Failed to install on a Linux machine

### ISSUE THREAD

**Issue by gongliyu** [RBigData/pbdMPI#62]
Hi, I tried to install pbdMPI on a cluster, but got an error message as follows:

> install.packages("pbdMPI")
Installing package into '/home/lgo232/R/x86_64-redhat-linux-gnu-library/3.4'
(as 'lib' is unspecified)
trying URL 'https://mirrors.nics.utk.edu/cran/src/contrib/pbdMPI_0.3-3.tar.gz'
Content type 'application/x-gzip' length 499763 bytes (488 KB)
==================================================
downloaded 488 KB

* installing *source* package 'pbdMPI' ...
** package 'pbdMPI' successfully unpacked and MD5 sums checked
setting mpi include path from MPI_INCLUDE
configure: error: Must specify both the include and lib paths
ERROR: configuration failed for package 'pbdMPI'
* removing '/home/lgo232/R/x86_64-redhat-linux-gnu-library/3.4/pbdMPI'

The downloaded source packages are in
        '/tmp/RtmpnqYr4d/downloaded_packages'
Warning message:
In install.packages("pbdMPI") :
  installation of package 'pbdMPI' had non-zero exit status

It seems a problem happened when R try to compile some of the C/C++ source files.

**Comment by wrathematics** [comment]
Package configure was not able to automatically find MPI. You will have to specify the include and lib paths. See page 3 of [the pbdMPI vignette](https://github.com/RBigData/pbdMPI/blob/master/inst/doc/pbdMPI-guide.pdf) before section 1.3.

**Comment by gongliyu** [comment]
Thank you!
