### ISSUE TITLE
Sending big structure

### ISSUE THREAD

**Issue by sebastien-jalgos** [RBigData/pbdMPI#75]
Sending long vector fails because of the type checking:

`X <- integer(2 ^ 33)`
`send(X)`

> Error in send(X) : 
>   INTEGER() can only be applied to a 'integer', not a 'double'

This is because `spmd.check.type` sends an integer to give information about the size, sending doubles would be more appropriate

**Comment by snoweye** [comment]
Please check and send PR if needed. Thanks.

**Comment by seblamydlc** [comment]
It appears the merge request didn't fix the problem, a send_integer was left somewhere. I wrote and tested a fix, there is a PR coming shortly, hope you have time to check it out.

**Comment by go-ski** [comment]
Fixed in issue #81
