### ISSUE TITLE
isend buffer issue

### ISSUE THREAD

**Issue by krometis** [RBigData/pbdMPI#81]
When I paste the code from the isend() documentation (https://cran.r-project.org/web/packages/pbdMPI/pbdMPI.pdf) into a script and call 
`mpirun -np 2 Rscript --vanilla isend_demo.r `

I get the following error:
```
Error in .pbd_env$SPMD.DT$alc.func[[ct.buffer[1]]] : 
  attempt to select less than one element in integerOneIndex
Calls: recv -> recv -> spmd.check.type
Execution halted
```

When I replace isend() with send(), the error goes away. The full script is below. This is on a Slurm cluster; let me know if there's anything else I can provide to be helpful. It seems possible that this is fixed with the fix to issue #75 (which I don't think is available in CRAN yet) but I wanted to pass this along in case it is not.

```
suppressMessages(library(pbdMPI, quietly = TRUE))
init()
.comm.size <- comm.size()
.comm.rank <- comm.rank()
### Examples.
N <- 5
x <- (1:N) + N * .comm.rank
if(.comm.rank == 0){
y <- isend(matrix(x, nrow = 1))
} else if(.comm.rank == 1){
y <- recv()
}
comm.print(y, rank.print = 1)
### Finish.
finalize()
```

**Comment by snoweye** [comment]
Thank for the example, I will take a look when I have time on this. I am not sure if `isend()` had been considered to fix in that issue. In R, it is really difficult to have benefits to use `isend()` safely. The buffer was designed only to make sure it may be sent out safely. The performance could be worse than the a simple `send()`.

**Comment by snoweye** [comment]
Thanks. Fix at [here](https://github.com/RBigData/pbdMPI/pull/82). Actually, the handshaking was not implemented for `isend()`. The example should be fine now. @krometis

**Comment by krometis** [comment]
Thank you for taking care of it! What is the timeline for these changes to
wind up in the official version on CRAN (
https://cran.r-project.org/package=pbdMPI)?

Justin Krometis
Advanced Research Computing
http://www.arc.vt.edu
jkrometis@vt.edu
