### ISSUE TITLE
Having issues installing packages

### ISSUE THREAD

**Issue by McChickenNuggets** [RBigData/pbdMPI#85]
> install.packages('pbdMPI')
Installing package into ‘C:/Users/Jaune/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
试开URL’https://cran.rstudio.com/bin/windows/contrib/3.6/pbdMPI_0.4-3.zip'
Content type 'application/zip' length 1045950 bytes (1021 KB)
downloaded 1021 KB

package ‘pbdMPI’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Jaune\AppData\Local\Temp\RtmpwhqtFr\downloaded_packages
> suppressPackageStartupMessages({
+     library(pbdMPI)
+ })
 错误: package or namespace load failed for ‘pbdMPI’:
 loadNamespace()里算'pbdMPI'时.onLoad失败了，详细内容：
  调用: inDL(x, as.logical(local), as.logical(now), ...)
  错误: 无法载入共享目标对象‘C:/Users/Jaune/Documents/R/win-library/3.6/pbdMPI/libs/i386/pbdMPI.dll’：:
  LoadLibrary failure:  找不到指定的模块。 

I try to uninstall Rstudio and search among Google, and I still havent figured out how to solve this issue.

**Comment by snoweye** [comment]
Please read pbdMPI vignette at
https://cran.r-project.org/web/packages/pbdMPI/vignettes/pbdMPI-guide.pdf
Item 12 in Section 8.3 on Page 25.

**Comment by McChickenNuggets** [comment]
Thanks. It worked now after I install msmpi.
